# Imagen base: desde donde partimos
FROM python:3.10-slim

# Mensaje al construir la imagen
RUN echo "Construyendo la imagen... listo - RUN" 

# instrucción que se ejecuta cuando el contenedor arranca.
CMD ["echo", "Hola desde Docker -  CMD"]